"""HMAC integrity chain for run-authority files (RC4).

`state.yaml` and the red-proof sidecars get the same defense-in-depth the TDD
path has: every write by an owned entry point is sealed (HMAC over seq +
prev-hmac + content bytes, key workspace-local); every read verifies. An
out-of-band mutation — any bypass of the string guards, via any tool — is
*detected at the next read* rather than trusted.

Threat model (per RC4): a *drifting* agent writing around the guards, not a
deliberate adversary that reads the key and re-implements the chain. The
guards are the fast-fail; this chain is the guarantee. Rolling back BOTH a
file and its seal to an older self-consistent pair is a residual (noted, out
of scope — the mirror history and reviewer remain backstops).
"""
from __future__ import annotations

import hashlib
import hmac as _hmac
import json
import os
import secrets
from pathlib import Path


class IntegrityError(Exception):
    """Sealed file fails chain verification — out-of-band mutation detected."""


def _key_path(workspace: Path) -> Path:
    return workspace / ".claude" / "context" / ".harness-key"


def load_key(workspace: Path) -> bytes:
    """Read-only key load: REFUSES when absent instead of minting one
    (a cwd-defaulted --workspace pointed inside a repo could silently
    mint a fresh random key there, and report the genuinely sealed
    state.yaml as an 'integrity seal mismatch' — a phantom tamper alarm
    plus a stray key). Every load/verify/save path uses this; only
    bootstrap — the one legitimate key-creation moment — goes through
    load_or_create_key."""
    path = _key_path(workspace)
    if not path.exists():
        raise IntegrityError(
            f"no integrity key at {path} — wrong --workspace? Runs live at "
            "<workspace>/ai/<run-name> and the key is created once at "
            "workspace bootstrap; pass --workspace explicitly or run from "
            "the workspace root")
    return _read_key(path)


def load_or_create_key(workspace: Path) -> bytes:
    path = _key_path(workspace)
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        # O_CREAT|O_EXCL with 0600 at open (adversarial-review finding: the
        # old write_text-then-chmod was world-readable for a window AND two
        # concurrent first-runs could both see "missing" and race the
        # write, silently invalidating the loser's seals — with O_EXCL the
        # loser just reads the winner's key).
        try:
            fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        except FileExistsError:
            pass  # a concurrent creator won — use its key
        else:
            try:
                os.write(fd, secrets.token_hex(32).encode("utf-8"))
            finally:
                os.close(fd)
    return _read_key(path)


def _read_key(path: Path) -> bytes:
    text = path.read_text(encoding="utf-8").strip()
    try:
        key = bytes.fromhex(text)
    except ValueError as exc:
        raise IntegrityError(
            f"{path}: key file is corrupt (not hex) — every seal in this "
            "workspace is unverifiable until it is restored; if it is "
            "unrecoverable, delete it and `harness reseal` each run"
        ) from exc
    if not key:
        raise IntegrityError(
            f"{path}: key file is empty — restore it, or delete it and "
            "`harness reseal` each run")
    return key


def _seal_path(path: Path) -> Path:
    return path.with_name(path.name + ".hmac")


def _digest(key: bytes, seq: int, prev: str, content: bytes,
            label: str = "") -> str:
    # `label` binds the seal to an IDENTITY, not just content (adversarial-
    # review finding: a red-proof sealed without one could be file-copied to
    # another task's proof path and still verify — the seal proved "this
    # content is authentic", never "this content belongs HERE").
    #
    # Domain separation (adversarial-review finding: the old
    # `{seq}:{prev}:{label}:` form let an empty-label seal over
    # `b"redproof:T1:"+X` collide with a `label="redproof:T1"` seal over X).
    # The labelled form now carries a `\x1f`-delimited length field that the
    # empty-label form never emits; sealed content (yaml/json) never begins
    # with `\x1f`, so the two message spaces can't overlap. Empty-label
    # (state.yaml) encoding is byte-for-byte UNCHANGED, so existing
    # state.yaml seals keep verifying; only red-proofs (short-lived,
    # regenerated by verify-red) use the new labelled encoding.
    if label:
        prefix = f"{seq}:{prev}:".encode("utf-8") + \
            b"\x1f" + str(len(label)).encode("utf-8") + b"\x1f" + \
            label.encode("utf-8") + b"\x1f"
    else:
        prefix = f"{seq}:{prev}:".encode("utf-8")
    return _hmac.new(key, prefix + content, hashlib.sha256).hexdigest()


def seal(path: Path, content: bytes, key: bytes, label: str = "") -> None:
    """Write `content` to `path` and chain-seal it (single-writer callers
    hold the run lock, so read-increment-write on the seal is safe).

    Content and seal are still two separate files (changing that would mean
    `state.yaml` is no longer plain-text `cat`-able, and every `verify()`
    caller — including `show-redproof`'s raw `json.loads(verify(...))` —
    would need to unwrap an envelope first); a crash in the narrow window
    between the two `os.replace` calls is a residual, same class as the
    module's own documented threat-model boundary (out-of-band mutation
    that LOOKS like tampering) — `harness reseal` is the human-invoked,
    logged recovery path for it. What this DOES fully close: the seal
    file's own write used to be a plain `write_text` (not atomic even by
    itself) — a crash mid-write left a truncated, unparseable seal file
    even without content changing at all. Both writes are now atomic."""
    seal_file = _seal_path(path)
    seq, prev = 0, ""
    if seal_file.exists():
        old = json.loads(seal_file.read_text(encoding="utf-8"))
        seq, prev = old["seq"] + 1, old["hmac"]
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_bytes(content)
    os.replace(tmp, path)  # atomic content swap
    seal_tmp = seal_file.with_name(seal_file.name + ".tmp")
    seal_tmp.write_text(
        json.dumps({"seq": seq, "prev": prev,
                    "hmac": _digest(key, seq, prev, content, label)}),
        encoding="utf-8",
    )
    os.replace(seal_tmp, seal_file)  # atomic seal swap


def reseal(path: Path, key: bytes, label: str = "") -> dict:
    """`harness reseal` — human-invoked recovery when a seal is missing,
    truncated, or mismatched (a crash between the content and seal writes
    in `seal()` above, OR a genuinely tampered file — this module can't
    tell the two apart, per its own documented threat-model boundary).
    Reseals the file's CURRENT on-disk content as a fresh chain baseline
    (continuing seq/prev from a still-readable prior seal, or starting a
    new chain at seq 0 if the seal itself is unreadable). Never invoked
    automatically — the caller (harness reseal) always logs a `reseal`
    event, and this is a footgun precisely because it can't distinguish
    recovery from laundering tampering, so it must always be a deliberate,
    visible human action."""
    if not path.exists():
        raise IntegrityError(f"{path}: nothing to reseal — file does not exist")
    content = path.read_bytes()
    seal_file = _seal_path(path)
    seq, prev = 0, ""
    if seal_file.exists():
        try:
            old = json.loads(seal_file.read_text(encoding="utf-8"))
            seq, prev = old["seq"] + 1, old["hmac"]
        except (json.JSONDecodeError, KeyError):
            pass  # truncated/corrupt seal itself — start a fresh chain at seq 0
    # `label` mirrors seal()/verify() so reseal stays correct if recovery is
    # ever extended beyond state.yaml (the `reseal` CLI verb is state.yaml-
    # only today, empty label — adversarial-review LOW: this param was
    # missing, so a resealed labelled file would fail its labelled verify).
    digest = _digest(key, seq, prev, content, label)
    seal_tmp = seal_file.with_name(seal_file.name + ".tmp")
    seal_tmp.write_text(json.dumps({"seq": seq, "prev": prev, "hmac": digest}),
                        encoding="utf-8")
    os.replace(seal_tmp, seal_file)
    return {"seq": seq, "prev": prev, "hmac": digest}


def verify(path: Path, key: bytes, label: str = "") -> bytes:
    """Return `path`'s content after verifying its seal; raise IntegrityError
    on any mismatch (tampered content, missing/forged seal, or a seal made
    under a different `label` — i.e. an authentic file copied to a path/
    identity it doesn't belong to)."""
    seal_file = _seal_path(path)
    if not seal_file.exists():
        raise IntegrityError(f"{path}: no integrity seal — out-of-band write suspected")
    meta = json.loads(seal_file.read_text(encoding="utf-8"))
    content = path.read_bytes()
    expected = _digest(key, meta["seq"], meta["prev"], content, label)
    if not _hmac.compare_digest(expected, meta.get("hmac", "")):
        raise IntegrityError(f"{path}: integrity seal mismatch — out-of-band mutation detected")
    return content
